# Generated by Django 4.2.2 on 2023-07-11 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=180, verbose_name='Titulo')),
                ('imagen', models.TextField(null=True, verbose_name='Imagen')),
                ('description', models.TextField(null=True, verbose_name='Descripcion')),
                ('precio', models.IntegerField(null=True, verbose_name='precio')),
            ],
        ),
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=180, verbose_name='Nombre')),
                ('apellidos', models.TextField(null=True, verbose_name='Apellido')),
                ('telefono', models.IntegerField(null=True, verbose_name='Telefono')),
                ('propiedad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finca.propiedad', verbose_name='Propiety')),
            ],
        ),
    ]
