# Generated by Django 4.2.2 on 2023-07-26 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos',
            name='propiedad',
        ),
    ]
